const SUPABASE_URL = 'https://cdnrasyagnzejqouuuju.supabase.co';
const SUPABASE_KEY = 'sb_publishable_xvHhtuwTRsOjsBclxVxzGw_QgjnWizZ';

const AUTH_EMAIL_DOMAIN = '@chaia.finance';

const APP_NAME = 'Chaia Finance';
const INSTALL_SQL = [
  'create table if not exists public.banks (',
  '  id uuid primary key default gen_random_uuid(),',
  '  name text not null,',
  '  kind text not null default \'credit\',',
  '  balance numeric not null default 0,',
  '  debt numeric not null default 0,',
  '  invoice_day int,',
  '  color text,',
  '  created_at timestamptz default now()',
  ');',
  'create table if not exists public.transactions (',
  '  id uuid primary key default gen_random_uuid(),',
  '  bank_id uuid references public.banks(id) on delete set null,',
  '  date date not null,',
  '  raw_name text not null,',
  '  display_name text,',
  '  category text,',
  '  amount numeric not null,',
  '  type text not null,',
  '  source text not null default \'manual\',',
  '  created_at timestamptz default now()',
  ');',
  'create table if not exists public.aliases (',
  '  id uuid primary key default gen_random_uuid(),',
  '  raw_name text not null unique,',
  '  display_name text not null,',
  '  created_at timestamptz default now()',
  ');',
  'create table if not exists public.bills (',
  '  id uuid primary key default gen_random_uuid(),',
  '  name text not null,',
  '  category text,',
  '  amount numeric not null default 0,',
  '  kind text not null default \'monthly\',',
  '  due_day int,',
  '  due_date date,',
  '  bank_id uuid references public.banks(id) on delete set null,',
  '  active boolean not null default true,',
  '  created_at timestamptz default now()',
  ');',
  'alter table public.bills add column if not exists kind text not null default \'monthly\';',
  'alter table public.bills add column if not exists due_date date;',
  'alter table public.bills add column if not exists template_id uuid;',
  'alter table public.bills alter column due_day drop not null;',
  'alter table public.bill_templates add column if not exists category text;',
  'alter table public.bill_templates add column if not exists bank_id uuid references public.banks(id) on delete set null;',
  'create table if not exists public.bill_templates (',
  '  id uuid primary key default gen_random_uuid(),',
  '  name text not null,',
  '  kind text not null default \'fixed\',',
  '  amount numeric,',
  '  due_day int not null,',
  '  category text,',
  '  bank_id uuid references public.banks(id) on delete set null,',
  '  active boolean not null default true,',
  '  created_at timestamptz default now()',
  ');',
  'create table if not exists public.bill_payments (',
  '  id uuid primary key default gen_random_uuid(),',
  '  bill_id uuid references public.bills(id) on delete cascade,',
  '  month text not null,',
  '  amount numeric not null,',
  '  paid_at date not null default current_date,',
  '  created_at timestamptz default now(),',
  '  unique (bill_id, month)',
  ');',
  'create table if not exists public.settings (',
  '  key text primary key,',
  '  value jsonb not null,',
  '  updated_at timestamptz default now()',
  ');',
  'create index if not exists idx_tx_date on public.transactions(date);',
  'create index if not exists idx_tx_bank on public.transactions(bank_id);',
  'alter table public.banks enable row level security;',
  'alter table public.transactions enable row level security;',
  'alter table public.aliases enable row level security;',
  'alter table public.bills enable row level security;',
  'alter table public.bill_payments enable row level security;',
  'alter table public.settings enable row level security;',
  'alter table public.bill_templates enable row level security;',
  'drop policy if exists "family_access" on public.banks;',
  'create policy "family_access" on public.banks for all to authenticated using (true) with check (true);',
  'drop policy if exists "family_access" on public.transactions;',
  'create policy "family_access" on public.transactions for all to authenticated using (true) with check (true);',
  'drop policy if exists "family_access" on public.aliases;',
  'create policy "family_access" on public.aliases for all to authenticated using (true) with check (true);',
  'drop policy if exists "family_access" on public.bills;',
  'create policy "family_access" on public.bills for all to authenticated using (true) with check (true);',
  'drop policy if exists "family_access" on public.bill_payments;',
  'create policy "family_access" on public.bill_payments for all to authenticated using (true) with check (true);',
  'drop policy if exists "family_access" on public.settings;',
  'create policy "family_access" on public.settings for all to authenticated using (true) with check (true);',
  'drop policy if exists "family_access" on public.bill_templates;',
  'create policy "family_access" on public.bill_templates for all to authenticated using (true) with check (true);',
  'grant usage on schema public to anon, authenticated;',
  'grant all on all tables in schema public to anon, authenticated;',
  'grant all on all sequences in schema public to anon, authenticated;'
].join('\n');